### ISSUE TITLE
2.4.7 Version: The OpenAPI export of top-level menus (Controller) is the class name instead of the specified comments bug.

### ISSUE THREAD

**Issue by wanj3366** [TongchengOpenSource/smart-doc#302] opened 2022-06-27 09:09 UTC
## Your Environment (Your Use Environment)
* smart-doc version: 2.4.7
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): apache-maven-3.6.3

## Expected Behavior (Expected Outcome)
The top-level menu names exported by OpenAPI are expected to match the class comments.
![Expected Result](https://user-images.githubusercontent.com/12858721/175902364-c7731fa2-30de-4f98-afd9-8b7197cc4964.jpg)

## Current Behavior (Current Outcome)
![Current Situation](https://user-images.githubusercontent.com/12858721/175902386-37bd354d-c1ac-467a-88a1-345a4f3cf9ca.jpg)

## Possible Solution (Bug Resolution Suggestion)
The class comments should be displayed.
![1656320873565](https://user-images.githubusercontent.com/12858721/175903253-8ac041c3-523c-47cc-b632-70ee8ce3d753.jpg)

## Steps to Reproduce (Steps to Reproduce the Bug)
Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant:
1.
2.
3.
4.

## Context (Impact of the Bug)
Increases the difficulty of frontend and backend interface communication and integration, making it hard to identify.

**Comment by shalousun** [comment] 2022-06-28 02:33
@wanj3366 This is a duplicate of issue https://github.com/smart-doc-group/smart-doc/issues/296

**Closed as completed** 2022-07-09 08:27 UTC
Labels: bug
